### ISSUE TITLE
Some remarks about the organization of this repository

### ISSUE THREAD

**Issue by HBelusca** [reactos/wallpapers#2]
It would be great to keep a similar organization of this repository as it is already in our master:
https://github.com/reactos/reactos/tree/master/modules/wallpapers
namely, with subdirectories for the different wallpapers (missing would be putting the Mizu ones into a subdir).

The current Wallpapers.txt file in this new looks instead like some sort of LICENSE file: it should be renamed accordingly.

Finally, there is missing the nice summary table as in the ReadMe.txt file of current master: https://github.com/reactos/reactos/blob/1bc6c900869fe1a01279d199a7a0f7452b145dde/modules/wallpapers/ReadMe.txt

**Comment by katahiromz** [comment]
I have a question.

Can we directly choose the image file of the sub-directory from `desk.cpl`?

**Comment by katahiromz** [comment]
Note: You can PR on this repository.

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/6967

**Comment by katahiromz** [comment]
```txt
[Section]
Name = ReactOS Standard Wallpapers
Version = 3
License = CC BY
Description = The standard wallpaper collection for ReactOS
Category = 16
URLSite = https://github.com/reactos/wallpapers/
URLDownload = https://github.com/reactos/wallpapers/archive/refs/heads/main.zip
Installer = Generate
SizeBytes = ???

[Generate]
Files = wallpapers-main\README.txt|wallpapers-main\LICENSE.txt|wallpapers-main\data\Angelus\ReactOS\*|wallpapers-main\data\Mizu\*
Dir = %SystemRoot%\Web\Wallpaper
Lnk = !
```

**Comment by katahiromz** [comment]
`[Generate]` section `Files` entry will become complicated... @HBelusca Are you okay?

**Comment by HBelusca** [comment]
I think the complication of this `Files` entry should be reduced, but at the expense of making a script for building the zip file, that would iterate through the necessary files and subdirectories, and add the files in a flattened layout into the zip file.

**Comment by katahiromz** [comment]
https://github.com/reactos/wallpapers/pull/3

**Comment by learn-more** [comment]
> I think the complication of this `Files` entry should be reduced, but at the expense of making a script for building the zip file, that would iterate through the necessary files and subdirectories, and add the files in a flattened layout into the zip file.

That sounds like making it harder for no good reason?

**Comment by HBelusca** [comment]
PR #3 was merged and addresses my comments raised in this issue, so it can be closed!
